server:
  port: 9090

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/logistics?characterEncoding=utf-8&useSSL=false&serverTimezone = GMT
    username: songlian
    password: HuangWei17


mybatis-plus:
  mapper-locations: classpath*:com/songlian/logistics/dao/xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

